<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'A-stramien-formulier verzenden',
	'heading' => 'Nieuw formulier verzenden',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Ingeschakeld',
		'checkbox_unchecked' => 'Uitgeschakeld',
		'submitted_from' => 'Formulier verzonden op website: %s',
		'submitted_by' => 'IP-adres van bezoeker: %s',
		'too_many_submissions' => 'Te veel recente inzendingen van dit IP',
		'failed_to_send_email' => 'Verzenden van e-mail is mislukt',
		'invalid_reCAPTCHA_private_key' => 'Ongeldige reCAPTCHA-privécode.',
		'invalid_field_type' => 'Onbekend veldtype %s.',
		'invalid_form_config' => 'Het veld %s heeft een ongeldige configuratie.',
		'unknown_method' => 'Onbekende serveraanvraagmethode'
	),
	'email' => array(
		'from' => 'logopedieboxmeer@gmail.com',
		'to' => 'logopedieboxmeer@gmail.com'
	),
	'fields' => array(
		'custom_U1190' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Naam',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Naam is vereist.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Email is vereist.',
				'format' => 'Veld Email bevat een ongeldig e-mailadres.'
			)
		),
		'custom_U1195' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Bericht',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1199' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Telefoon',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Telefoon is vereist.'
			)
		)
	)
);

process_form($form);
?>
